package com.frontend.ventanaprincipal;

import com.frontend.menus.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author michael
 */
public class FramePrincipal extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Principal
     */
    IniciarPartidaPanel panelPartida = new IniciarPartidaPanel();
    NuevaPartidaPanel nuevaPartida = new NuevaPartidaPanel();
    PuntajesPanel puntajes = new PuntajesPanel();
    ColeccionTablerosPanel tableros = new ColeccionTablerosPanel();

    public FramePrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.nuevaPartidaButton.setEnabled(false);
        this.regresarButton.setVisible(false);
        iniciarPartidaButton.addActionListener(this);
        nuevaPartidaButton.addActionListener(this);
        puntajesButton.addActionListener(this);
        tablerosButton.addActionListener(this);
        salirButton.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorJPanel = new javax.swing.JPanel();
        menusJPanel = new javax.swing.JPanel();
        nuevaPartidaButton = new javax.swing.JButton();
        iniciarPartidaButton = new javax.swing.JButton();
        tablerosButton = new javax.swing.JButton();
        puntajesButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Batalla Naval");
        setMinimumSize(new java.awt.Dimension(733, 423));

        contenedorJPanel.setBackground(new java.awt.Color(0, 204, 204));
        contenedorJPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contenedorJPanel, java.awt.BorderLayout.CENTER);

        menusJPanel.setBackground(new java.awt.Color(0, 0, 0));
        menusJPanel.setLayout(new javax.swing.BoxLayout(menusJPanel, javax.swing.BoxLayout.LINE_AXIS));

        nuevaPartidaButton.setBackground(new java.awt.Color(204, 204, 204));
        nuevaPartidaButton.setForeground(new java.awt.Color(0, 0, 0));
        nuevaPartidaButton.setText("Nueva Partida");
        nuevaPartidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaPartidaButtonActionPerformed(evt);
            }
        });
        menusJPanel.add(nuevaPartidaButton);

        iniciarPartidaButton.setBackground(new java.awt.Color(204, 204, 204));
        iniciarPartidaButton.setForeground(new java.awt.Color(0, 0, 0));
        iniciarPartidaButton.setText("Iniciar Partida");
        iniciarPartidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarPartidaButtonActionPerformed(evt);
            }
        });
        menusJPanel.add(iniciarPartidaButton);

        tablerosButton.setBackground(new java.awt.Color(204, 204, 204));
        tablerosButton.setForeground(new java.awt.Color(0, 0, 0));
        tablerosButton.setText("Colección de Tableros");
        tablerosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablerosButtonActionPerformed(evt);
            }
        });
        menusJPanel.add(tablerosButton);

        puntajesButton.setBackground(new java.awt.Color(204, 204, 204));
        puntajesButton.setForeground(new java.awt.Color(0, 0, 0));
        puntajesButton.setText("Puntajes");
        puntajesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajesButtonActionPerformed(evt);
            }
        });
        menusJPanel.add(puntajesButton);

        regresarButton.setBackground(new java.awt.Color(204, 204, 204));
        regresarButton.setForeground(new java.awt.Color(0, 0, 0));
        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });
        menusJPanel.add(regresarButton);

        salirButton.setBackground(new java.awt.Color(255, 0, 0));
        salirButton.setForeground(new java.awt.Color(0, 0, 0));
        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        menusJPanel.add(salirButton);

        getContentPane().add(menusJPanel, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        repintarPanel(contenedorJPanel);
        puntajesButton.setEnabled(true);
        tablerosButton.setEnabled(true);
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void nuevaPartidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaPartidaButtonActionPerformed
        repintarPanel(panelPartida);
        puntajesButton.setEnabled(false);
        tablerosButton.setEnabled(false);
        regresarButton.setVisible(true);
    }//GEN-LAST:event_nuevaPartidaButtonActionPerformed

    private void iniciarPartidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarPartidaButtonActionPerformed
        repintarPanel(nuevaPartida);
        tablerosButton.setVisible(false);
        puntajesButton.setVisible(false);
        regresarButton.setVisible(true);    }//GEN-LAST:event_iniciarPartidaButtonActionPerformed

    private void tablerosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablerosButtonActionPerformed
        repintarPanel(tableros);
        regresarButton.setVisible(true);    }//GEN-LAST:event_tablerosButtonActionPerformed

    private void puntajesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajesButtonActionPerformed
        repintarPanel(puntajes);
        regresarButton.setVisible(true);
    }//GEN-LAST:event_puntajesButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        confirmacionDeCerrar();
    }//GEN-LAST:event_salirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorJPanel;
    private javax.swing.JButton iniciarPartidaButton;
    private javax.swing.JPanel menusJPanel;
    private javax.swing.JButton nuevaPartidaButton;
    private javax.swing.JButton puntajesButton;
    private javax.swing.JButton regresarButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton tablerosButton;
    // End of variables declaration//GEN-END:variables

    public void repintarPanel(JPanel panel) {
        contenedorJPanel.removeAll();
        contenedorJPanel.add(panel);
        contenedorJPanel.revalidate();
        contenedorJPanel.repaint();
    }

    private void desabilitarBotonNuevaPartida() {
        nuevaPartidaButton.setEnabled(false);
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evento = ae.getSource();

        if (evento.equals(iniciarPartidaButton)) {

        } else if (evento.equals(nuevaPartidaButton)) {

        } else if (evento.equals(puntajesButton)) {

        } else if (evento.equals(tablerosButton)) {

        } else if (evento.equals(regresarButton)) {
            puntajesButton.setEnabled(true);
            tablerosButton.setEnabled(true);
            repintarPanel(contenedorJPanel);
        } else if (evento.equals(salirButton)) {
            confirmacionDeCerrar();
        }
    }

    private void confirmacionDeCerrar() {
        int eleccion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "¿Salir?", 0);
        if (eleccion == 0) {
            System.exit(0);
        } else if (eleccion == 1) {
            JOptionPane.showMessageDialog(this, "Continua jugando");
        }
    }
}
