package com.frontend.ventanaprincipal;

import com.frontend.menus.IniciarPartidaPanel;
import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author michael
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorJPanel = new javax.swing.JPanel();
        menusJPanel = new javax.swing.JPanel();
        nuevaPartidaButton = new javax.swing.JButton();
        iniciarPartidaButton = new javax.swing.JButton();
        tablerosButton = new javax.swing.JButton();
        puntajesButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalla Naval");
        setMinimumSize(new java.awt.Dimension(733, 423));

        contenedorJPanel.setBackground(new java.awt.Color(0, 204, 204));
        contenedorJPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contenedorJPanel, java.awt.BorderLayout.CENTER);

        menusJPanel.setLayout(new javax.swing.BoxLayout(menusJPanel, javax.swing.BoxLayout.LINE_AXIS));

        nuevaPartidaButton.setBackground(new java.awt.Color(204, 204, 204));
        nuevaPartidaButton.setForeground(new java.awt.Color(0, 0, 0));
        nuevaPartidaButton.setText("Nueva Partida");
        nuevaPartidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaPartidaButtonActionPerformed(evt);
            }
        });
        menusJPanel.add(nuevaPartidaButton);

        iniciarPartidaButton.setBackground(new java.awt.Color(204, 204, 204));
        iniciarPartidaButton.setForeground(new java.awt.Color(0, 0, 0));
        iniciarPartidaButton.setText("Iniciar Partida");
        menusJPanel.add(iniciarPartidaButton);

        tablerosButton.setBackground(new java.awt.Color(204, 204, 204));
        tablerosButton.setForeground(new java.awt.Color(0, 0, 0));
        tablerosButton.setText("Colección de Tableros");
        menusJPanel.add(tablerosButton);

        puntajesButton.setBackground(new java.awt.Color(204, 204, 204));
        puntajesButton.setForeground(new java.awt.Color(0, 0, 0));
        puntajesButton.setText("Puntajes");
        menusJPanel.add(puntajesButton);

        salirButton.setBackground(new java.awt.Color(255, 0, 0));
        salirButton.setForeground(new java.awt.Color(0, 0, 0));
        salirButton.setText("Salir");
        menusJPanel.add(salirButton);

        getContentPane().add(menusJPanel, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaPartidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaPartidaButtonActionPerformed
        // TODO add your handling code here:
        IniciarPartidaPanel iniciarPartida = new IniciarPartidaPanel();
        nuevaPartidaButton.addActionListener((ActionListener) this);
        repintarPanel(iniciarPartida);
    }//GEN-LAST:event_nuevaPartidaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorJPanel;
    private javax.swing.JButton iniciarPartidaButton;
    private javax.swing.JPanel menusJPanel;
    private javax.swing.JButton nuevaPartidaButton;
    private javax.swing.JButton puntajesButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton tablerosButton;
    // End of variables declaration//GEN-END:variables

    public void repintarPanel(JPanel panel) {
        contenedorJPanel.removeAll();
        contenedorJPanel.add(panel);
        contenedorJPanel.revalidate();
        contenedorJPanel.repaint();

    }
}
