package com.frontend.ventanaymenus;

import com.backend.principal.Archivo;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author michael
 */
public class NuevaPartidaPanel extends javax.swing.JPanel {

    private JTextArea texto;
    BorderLayout borderLayout = new BorderLayout();

    /**
     * Creates new form NuevaPartida
     */
    public NuevaPartidaPanel() {
        initComponents();
        setVisible(true);
        panelBotones.setBackground(Color.DARK_GRAY);
        mostrarMapas(mostrarMensajeDeCargaDeArchivo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        cargarMapaBoton = new javax.swing.JButton();
        siguienteBoton = new javax.swing.JButton();
        panelPrevisualizador = new javax.swing.JPanel();

        cargarMapaBoton.setText("Cargar Mapa");
        cargarMapaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarMapaBotonActionPerformed(evt);
            }
        });

        siguienteBoton.setText("Siguiente");

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cargarMapaBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siguienteBoton)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarMapaBoton)
                    .addComponent(siguienteBoton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrevisualizadorLayout = new javax.swing.GroupLayout(panelPrevisualizador);
        panelPrevisualizador.setLayout(panelPrevisualizadorLayout);
        panelPrevisualizadorLayout.setHorizontalGroup(
            panelPrevisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPrevisualizadorLayout.setVerticalGroup(
            panelPrevisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelPrevisualizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrevisualizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarMapaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarMapaBotonActionPerformed
        JFileChooser archivoSeleccionado = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TH", ".th");
        
        //archivoSeleccionado.setFileFilter(filtro);
        archivoSeleccionado.showOpenDialog(null);
        System.out.println(archivoSeleccionado.getSelectedFile().getAbsolutePath());
        Archivo archivo = new Archivo();
        archivo.leerArchivoTh(archivoSeleccionado.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_cargarMapaBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarMapaBoton;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPrevisualizador;
    private javax.swing.JButton siguienteBoton;
    // End of variables declaration//GEN-END:variables

    public JTextArea mostrarMensajeDeCargaDeArchivo() {
        String mensajeInformativo = "Debe de subir un archivo con extensión \".th\", el formato debe ser el siguiente:”\n\n"
                + "		“~ Indica la posicion de una casilla normal de agua.”\n"
                + "		“B1 Indica la posición del barco de tamaño de una casilla”\n"
                + "		“B2 Indica la posición del barco de tamaño de dos casillas”\n"
                + "		“B3 Indica la posición del barco de tamaño de tres casillas”\n"
                + "		“T Indica la posición de una bomba tipo torpedo”\n"
                + "		“I Indica la posición de una bomba tipo misil”\n"
                + "		“O Indica la posición de una bomba tipo hecatombe”\n"
                + "		“«id» Indica el número o palabra con el que se identificará el mapa, el nombre definido en un mapa no puede repetirse.\n"
                + "              \nEstructura en el archivo\n\n"
                + "             tablero <<id>>\n"
                + "             dimension 5x5\n"
                + "             ~,B3,~,B1,~\n"
                + "             ~,B3,~,B2,B2\n"
                + "             ~,B3,~,T,~\n"
                + "             I,~,O,~,~\n"
                + "             ~,~,~,~,~\n"
                + "\nRECUERDE GUARDAR EL MAPA CON EXTENSION \".th\"";

        texto = new JTextArea(mensajeInformativo);
        texto.setBounds(50, 50, 300, 200);
        texto.setEditable(false);
        return texto;
    }

    private void mostrarMapas(JComponent texto) {
        panelPrevisualizador.setLayout(borderLayout);
        panelPrevisualizador.setBackground(Color.LIGHT_GRAY);
        panelPrevisualizador.add(texto);
    }
}
