package com.frontend.ventanaymenus;

import com.backend.principal.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class PuntajesPanel extends javax.swing.JPanel {

    private Usuario jugador;
    private String nombre;
    private int puntos;
    /**
     * Creates new form PuntajesPanel
     */
    public PuntajesPanel(Usuario jugador) {
        jugador = new Usuario("", 0);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelDatosJuego = new javax.swing.JPanel();
        panelDatosUsuario = new javax.swing.JPanel();
        puntosBoton = new javax.swing.JButton();
        historialBoton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelDatosJuego.setBackground(new java.awt.Color(102, 255, 102));
        panelDatosJuego.setLayout(new java.awt.BorderLayout());

        panelDatosUsuario.setBackground(new java.awt.Color(255, 255, 102));
        panelDatosUsuario.setPreferredSize(new java.awt.Dimension(644, 35));
        panelDatosUsuario.setLayout(new java.awt.GridBagLayout());

        puntosBoton.setText("Puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 19, 7, 0);
        panelDatosUsuario.add(puntosBoton, gridBagConstraints);

        historialBoton.setText("Registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 7, 438);
        panelDatosUsuario.add(historialBoton, gridBagConstraints);

        panelDatosJuego.add(panelDatosUsuario, java.awt.BorderLayout.PAGE_START);

        add(panelDatosJuego, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton historialBoton;
    private javax.swing.JPanel panelDatosJuego;
    private javax.swing.JPanel panelDatosUsuario;
    private javax.swing.JButton puntosBoton;
    // End of variables declaration//GEN-END:variables

    public void copiarDatos(String nombre, int puntos) {
        this.nombre = nombre;
        this.puntos = puntos;
    }
    
    public void mostrarNombrePuntos() {
        
    }
    
}