package com.frontend.menus;

import com.frontend.ventanaprincipal.JFramePrincipal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author michael
 */
public class MenuPanel extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form MenuPanel
     */
    JFramePrincipal ventanaPrincipal = new JFramePrincipal();
    private IniciarPartidaPanel iniciarPanel;
    private NuevaPartidaPanel nuevaPartida;
    private PuntajesPanel puntaje;
    private ColeccionTablerosPanel tableros;
    
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        iniciarBoton = new javax.swing.JButton();
        nuevaBoton = new javax.swing.JButton();
        puntajesBoton = new javax.swing.JButton();
        tableroBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        iniciarBoton.setText("Iniciar Partida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(102, 221, 0, 0);
        add(iniciarBoton, gridBagConstraints);

        nuevaBoton.setText("Nueva Partida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 221, 0, 0);
        add(nuevaBoton, gridBagConstraints);

        puntajesBoton.setText("Puntajes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 234, 0, 0);
        add(puntajesBoton, gridBagConstraints);

        tableroBoton.setText("Colección de Tablero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 190, 0, 187);
        add(tableroBoton, gridBagConstraints);

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 241, 117, 0);
        add(salirBoton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        ventanaPrincipal.confirmacionCerrar();
    }//GEN-LAST:event_salirBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarBoton;
    private javax.swing.JButton nuevaBoton;
    private javax.swing.JButton puntajesBoton;
    private javax.swing.JButton salirBoton;
    private javax.swing.JButton tableroBoton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evt = ae.getSource();
        
        if (evt.equals(iniciarBoton)) {
            iniciarPanel = new IniciarPartidaPanel();
            ventanaPrincipal.pintarPanel(iniciarPanel);
        } else if (evt.equals(nuevaBoton)) {
            nuevaPartida = new NuevaPartidaPanel();
            ventanaPrincipal.pintarPanel(nuevaPartida);
        } else if (evt.equals(puntajesBoton)) {
            puntaje = new PuntajesPanel();
            ventanaPrincipal.pintarPanel(puntaje);
        } else if (evt.equals(tableroBoton)) {
            tableros = new ColeccionTablerosPanel();
            ventanaPrincipal.pintarPanel(tableros);
        }
    }
}
