package com.frontend.ventanaymenus;

import com.backend.componentestablero.Casilla;
import com.backend.componentestablero.Tablero;
import com.backend.principal.Archivo;
import com.backend.principal.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author michael
 */
public class NuevaPartidaPanel extends javax.swing.JPanel {

    private Usuario jugador;
    private JTextArea texto;
    BorderLayout borderLayout = new BorderLayout();

    /**
     * Creates new form NuevaPartida
     */
    public NuevaPartidaPanel() {
        jugador = new Usuario("", 0);
        initComponents();
        setVisible(true);
        panelBotones.setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        cargarMapaBoton = new javax.swing.JButton();
        siguienteBoton = new javax.swing.JButton();
        panelPrevisualizador = new javax.swing.JPanel();

        cargarMapaBoton.setText("Cargar Mapa");
        cargarMapaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarMapaBotonActionPerformed(evt);
            }
        });

        siguienteBoton.setText("Siguiente");

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cargarMapaBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siguienteBoton)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarMapaBoton)
                    .addComponent(siguienteBoton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrevisualizadorLayout = new javax.swing.GroupLayout(panelPrevisualizador);
        panelPrevisualizador.setLayout(panelPrevisualizadorLayout);
        panelPrevisualizadorLayout.setHorizontalGroup(
            panelPrevisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPrevisualizadorLayout.setVerticalGroup(
            panelPrevisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelPrevisualizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrevisualizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarMapaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarMapaBotonActionPerformed
        JFileChooser archivoSeleccionado = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TH", ".th");

        //archivoSeleccionado.setFileFilter(filtro);
        archivoSeleccionado.showOpenDialog(null);
        Archivo archivo = new Archivo();
        archivo.leerArchivoTh(archivoSeleccionado.getSelectedFile().getAbsolutePath());
        Tablero tablero = new Tablero("", 8, 8);
        mostrarTablero((Casilla[][]) tablero.crearTablero());
        
    }//GEN-LAST:event_cargarMapaBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarMapaBoton;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPrevisualizador;
    private javax.swing.JButton siguienteBoton;
    // End of variables declaration//GEN-END:variables

    public void mostrarMapas(JComponent texto) {
        FramePrincipal principal = new FramePrincipal();
        //panelPrevisualizador.setLocation((principal.getWidth() / 2) - 400, (principal.getHeight() / 2) - 250);

        panelPrevisualizador.remove(texto);
        panelPrevisualizador.setLayout(new FlowLayout());
        //panelPrevisualizador.setSize(new Dimension(900, 500));
        panelPrevisualizador.setBackground(Color.LIGHT_GRAY);
        panelPrevisualizador.add(texto);
    }

    public void mostrarTablero(Casilla[][] mapa) {
        int tamaño = ((int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight() / mapa.length)) * 2 / 3;
        int posicionX = 10;
        int posicionY = 10;
        int anchoCasilla;
        int largoCasilla = 0;

        for (int i = 0; i < mapa.length; i++) {
            anchoCasilla = panelPrevisualizador.getWidth() / mapa.length - 5;
            for (int j = 0; j < mapa[i].length; j++) {

                largoCasilla = panelPrevisualizador.getHeight() / mapa[i].length - 5;
                mapa[i][j] = new Casilla(tamaño);
                mapa[i][j].setBounds(posicionX, posicionY, anchoCasilla, largoCasilla);
                mostrarMapas(mapa[i][j]);
                posicionX += anchoCasilla + 5;
            }
            posicionX = 10;
            posicionY += largoCasilla + 5;
        }

    }
}
