package com.frontend.ventanaymenus;

import com.backend.principal.Archivo;
import com.backend.principal.Usuario;
import java.awt.Color;
import java.awt.FlowLayout;
import java.time.LocalTime;
import javax.swing.JTextArea;

/**
 *
 * @author michael
 */
public class PuntajesPanel extends javax.swing.JPanel {

    private Usuario jugador;
    private String nombre;
    private int puntos;
    LocalTime hora = LocalTime.now();

    /**
     * Creates new form PuntajesPanel
     */
    public PuntajesPanel(Usuario jugador) {
        jugador = new Usuario("", 0);
        initComponents();
        setVisible(true);
    }

    public PuntajesPanel() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelDatosJuego = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        puntosBoton = new javax.swing.JButton();
        historialBoton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelDatosJuego.setBackground(new java.awt.Color(102, 255, 102));
        panelDatosJuego.setLayout(new java.awt.BorderLayout());

        panelBotones.setBackground(new java.awt.Color(255, 255, 102));
        panelBotones.setPreferredSize(new java.awt.Dimension(644, 35));
        panelBotones.setLayout(new java.awt.GridBagLayout());

        puntosBoton.setText("Puntos");
        puntosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntosBotonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 19, 7, 0);
        panelBotones.add(puntosBoton, gridBagConstraints);

        historialBoton.setText("Registro");
        historialBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialBotonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 7, 438);
        panelBotones.add(historialBoton, gridBagConstraints);

        panelDatosJuego.add(panelBotones, java.awt.BorderLayout.PAGE_START);

        add(panelDatosJuego, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void puntosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntosBotonActionPerformed
        mostrarPuntajes();
    }//GEN-LAST:event_puntosBotonActionPerformed

    private void historialBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialBotonActionPerformed
        mostrarHistorial();
    }//GEN-LAST:event_historialBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton historialBoton;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatosJuego;
    private javax.swing.JButton puntosBoton;
    // End of variables declaration//GEN-END:variables

    public void copiarDatos(String nombre, int puntos) {
        this.nombre = nombre;
        this.puntos = puntos;
    }

    public void mostrarPuntajes() {
        Archivo avn = new Archivo();
        avn.crearArchivoAvn("Michael", " ", hora);
    }

    public void mostrarHistorial() {
        Archivo war = new Archivo();
        war.crearArchivoWar(" ", 0);
    }

    public void mostrarContenido(String texto) {
        JTextArea textoLeido = new JTextArea(texto);
        panelDatosJuego.removeAll();
        panelDatosJuego.setLayout(new FlowLayout());
        panelDatosJuego.setBackground(Color.LIGHT_GRAY);
        panelDatosJuego.add(textoLeido);
    }

}
